name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker Image
        run: |
          docker build -t my-docker-repo/payment-service:latest .

      - name: Push Docker Image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker tag my-docker-repo/payment-service:latest my-docker-repo/order-service:latest
          docker push my-docker-repo/payment-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/payment-service-deployment.yaml
          kubectl apply -f k8s/payment-service-service.yaml
          kubectl apply -f k8s/hpa.yaml
          kubectl rollout restart deployment payment-service
